version: '3'
services:
  web:
    image: node:10.1.0-alpine
    #image: node:9.11.1
    working_dir: /app/my-app/
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
